CAM:
  TEST_FREQ: 1
  TRAIN_FREQ: 40
  VAL_FREQ: 40
  ENABLE: False
DATA:
  AUGMENT: True
  IMAGE_RESIZE: (224, 224)
  LABEL_DICT: darpa_labels.json
  LABEL_FEATURES: ['sliding']
  LABEL_NAMES: ['no-sliding', 'sliding']
  MASK1: 
  MASK2: 
  MULTI_CLIP_EVAL: True
  NO_MULTI_CLIP: 4
  NUM_CLASS: 2
  NUM_FOLDS: 3
  NUM_MASKS: 0
  PROBE: Linear
  RANDOM_SPLIT_TRIAL: R1
  REPROCESS: False
  ROOT_PATH: data1/datasets/
  TEST_SPLIT: 0.2
  TRAIN_FOLDS: ['C', 'B']
  UPSAMPLE: True
  VAL_FOLDS: ['A']
  TEST_FOLDS: ['D']
EXPERIMENT:
  DATASET: DARPA-Dataset
  MODE: Train
  MODEL: tsm
  NAME: Pneumothorax_Exps
  TRIAL: Rct_SavgDropTmaxCls_T7
LOGGER:
  WANDB: online
MODEL:
  BACKBONE: resnet18
  CHECK_POINT: 
  DROPOUT: 0.5
  MODALITY: RGB
  PRETRAIN: imagenet
  ST_CONCENSUS: SavgDropTmaxCls
  MULTI_TASK: False
SOLVER:
  EPOCHS: 100
  INIT_LR: 0.0001
  LOSS_FUNC: cross_entropy
  OPTIMIZER: adam
  TEST_BATCH_SIZE: 8
  TRAIN_BATCH_SIZE: 4
SYSTEM:
  NUM_GPUS: [1]
  NUM_WORKERS: 16
  PIN_MEMORY: True
VIDEO_DATA:
  CLIP_WIDTH: 15
  TYPE: crop_image_rct
VIDEO_TEST_DATA:
  LABEL_DICT: []